### ISSUE TITLE
Error on 'git push heroku master'

### ISSUE THREAD

**Issue by arthurcolle** [HashNuke/heroku-buildpack-elixir#45]
I've successfully used this buildpack over the last week for this app: https://extrophus.herokuapp.com

I just started getting this error though:

```
Counting objects: 9, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (9/9), done.
Writing objects: 100% (9/9), 773 bytes | 0 bytes/s, done.
Total 9 (delta 7), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Fetching custom git buildpack... done
remote: -----> elixir app detected
remote: -----> Checking Erlang and Elixir versions
remote:        Will use the following versions:
remote:        * Stack cedar-14
remote:        * Erlang 17.2
remote:        * Elixir branch master
remote:        Will export the following config vars:
remote:        * Config vars DATABASE_URL
remote:        * MIX_ENV=prod
remote: -----> Stack changed, will rebuild
remote: -----> Fetching Erlang 17.2
remote: -----> Installing Erlang 17.2 (changed)
remote:
remote: -----> Fetching Elixir master
remote: -----> Installing Elixir master (changed)
remote: -----> Installing Hex
remote: 2015-06-21 01:58:12 URL:https://s3.amazonaws.com/s3.hex.pm/installs/1.0.0/hex.ez [262010/262010] -> "/app/.mix/archives/hex.ez" [1]
remote: * creating .mix/archives/hex.ez
remote: ** (MatchError) no match of right hand side value: {:error, :bad_directory}
remote:     (mix) lib/mix/tasks/archive.install.ex:68: Mix.Tasks.Archive.Install.install_archive/2
remote:     (mix) lib/mix/cli.ex:60: Mix.CLI.run_task/2
remote:     (elixir) lib/code.ex:363: Code.require_file/2
remote:
remote: -----> Installing rebar
remote: * creating .mix/rebar
remote: -----> Fetching app dependencies with mix
remote: Could not find hex, which is needed to build dependency :phoenix
remote: Shall I install hex? [Yn] ** (Mix) Could not find a SCM for dependency :phoenix from Trophus.Mixfile
remote:
remote:  !     Push rejected, failed to compile elixir app
remote:
remote: Verifying deploy...
remote:
remote: !	Push rejected to extrophus.
remote:
To https://git.heroku.com/extrophus.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/extrophus.git'
```

**Comment by arthurcolle** [comment]
This is my buildpack:
```
erlang_version=17.2
elixir_version=(branch master)
always_rebuild=true
```

Note, this has been working fine everyday since I started using it about a week ago. In fact a build succeeded a few hours ago and this just started happening.

**Comment by arthurcolle** [comment]
It started to work with this buildpack:

```
erlang_version=17.5
elixir_version=1.0.4
always_rebuild=true
```

**Comment by ericmj** [comment]
The erlang version you specified is too old to work with elixir master. Also, if you remove always_rebuild your builds will be much faster.
