### ISSUE TITLE
Ability to lock hex version

### ISSUE THREAD

**Issue by fbjork** [HashNuke/heroku-buildpack-elixir#49]
I'm getting this message when pushing my app now that Elixir 1.1 is out:

```
Hex was built against against Elixir v1.1.0-rc.0 and you are running v1.0.5, please run `mix local.hex` to update to a matching version
```

Which in turn causes the compilation to fail:

```
       == Compilation error on file lib/inventory_service/endpoint.ex ==
       ** (Protocol.UndefinedError) protocol Access not implemented for {:system, "DATABASE_URL"}
       (elixir) lib/access.ex:1: Access.impl_for!/1
       (elixir) lib/access.ex:33: Access.get/2
       lib/inventory_service/endpoint.ex:2: (module)
       (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
```

**Comment by ericmj** [comment]
The Hex version warning was due to an error in the release of Hex that has been fixed now. If you deploy again it will be fixed.

The error you get is very likely unrelated.
